<?php

declare(strict_types=1);

return [
    [
        'number' => '01',
        'title' => 'Fuerza bruta',
        'risk' => 'Alto',
        'status' => 'En desarrollo',
        'owasp' => 'A07:2021 — Identification and Authentication Failures',
        'url' => '/login-security.php',
    ],
    [
        'number' => '02',
        'title' => 'Ejecución de comandos',
        'risk' => 'Crítico',
        'status' => 'Pendiente',
        'owasp' => 'A03:2021 — Injection',
        'url' => '/command.php',
    ],
    [
        'number' => '03',
        'title' => 'Inclusión de archivos',
        'risk' => 'Alto',
        'status' => 'Pendiente',
        'owasp' => 'A01:2021 — Broken Access Control',
        'url' => '/file-include.php',
    ],
    [
        'number' => '04',
        'title' => 'SQL Injection',
        'risk' => 'Crítico',
        'status' => 'Pendiente',
        'owasp' => 'A03:2021 — Injection',
        'url' => '/sqli.php',
    ],
    [
        'number' => '05',
        'title' => 'Blind SQL Injection',
        'risk' => 'Crítico',
        'status' => 'Pendiente',
        'owasp' => 'A03:2021 — Injection',
        'url' => '/blind-sqli.php',
    ],
    [
        'number' => '06',
        'title' => 'Carga de archivos',
        'risk' => 'Crítico',
        'status' => 'Pendiente',
        'owasp' => 'A04:2021 — Insecure Design',
        'url' => '/upload.php',
    ],
    [
        'number' => '07',
        'title' => 'XSS Reflected',
        'risk' => 'Medio',
        'status' => 'Pendiente',
        'owasp' => 'A03:2021 — Injection',
        'url' => '/xss-reflected.php',
    ],
    [
        'number' => '08',
        'title' => 'XSS Stored',
        'risk' => 'Alto',
        'status' => 'Pendiente',
        'owasp' => 'A03:2021 — Injection',
        'url' => '/xss-stored.php',
    ],
    [
        'number' => '09',
        'title' => 'XSS DOM',
        'risk' => 'Medio',
        'status' => 'Pendiente',
        'owasp' => 'A03:2021 — Injection',
        'url' => '/xss-dom.php',
    ],
    [
        'number' => '10',
        'title' => 'Cabeceras y cookies',
        'risk' => 'Informativo',
        'status' => 'Pendiente',
        'owasp' => 'A05:2021 — Security Misconfiguration',
        'url' => '/security-info.php',
    ],
];